### PR TITLE
[FFM-1263] flag rules evaluations, repository with persistent

### PR DESCRIPTION
**Pull request by enver-bisevac**
Repository patternt with cache support
Flag rules evaluations

### CODE REVIEW

**Review by davejohnston — COMMENTED** [review]
This looks good to me (though I'm not experienced in Node).   The repository pattern and evaluator seem like a good approach here.

**Review by chrisblakely01 — COMMENTED** [review]
Looks pretty good! Do you think we should put some unit tests in?

**Comment by enver-bisevac** [comment]
> Looks pretty good! Do you think we should put some unit tests in?

Yes, after we all agree this is the way we should go. Evaluator should be 100% covered, that is for us most important part.

**Comment by chrisblakely01** [comment]
> > Looks pretty good! Do you think we should put some unit tests in?
> 
> Yes, after we all agree this is the way we should go. Evaluator should be 100% covered, that is for us most important part.

Cool, sounds good to me

**Review by chrisblakely01 — APPROVED** [review]

**Pull request merged**
